require:    
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - 'app/views/**/*'
    
Layout/LineLength:
  Max: 100

Metrics/MethodLength: 
  Max: 30

# The guiding principle of classes is SRP, SRP can't be accurately measured by LoC
Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/AbcSize:
 Max: 45

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature'] 

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: true
  EnforcedStyle: should 

RSpec/Capybara/FeatureMethods:
  EnabledMethods: ['feature', 'given', 'given!', 'scenario', 'background']

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/feature/**/*'

RSpec/ExampleLength:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false